### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by bungle** [eknkc/tsort#1]
``` js
var tsort = require('tsort');
var g = tsort();
g.add("3", "8");
g.add("3", "10");
g.add("5", "11");
g.add("7", "8");
g.add("7", "11");
g.add("8", "9");
g.add("11", "2");
g.add("11", "9");
g.add("11", "10");
console.dir(g.sort());
```

This will output:

``` js
[ '5', '7', '11', '2', '3', '8', '9', '10' ]
```

That is incorrect.

Correct would be something like this:

``` js
[ '7', '5', '3', '11', '8', '10', '2', '9' ]
```

**Comment by eknkc** [comment]
Which part is incorrect? The resulting order preserves all constraints that you supplied as far as I can tell.

**Comment by bungle** [comment]
This example is directly from here:
https://en.wikipedia.org/wiki/Tsort#Examples

E.g. 5, 7, and 3 are top level they should be first (?).

**Comment by eknkc** [comment]
Ah I see, but there is no single correct topological order for a graph like this. You can have multiple correct outputs and `[ '5', '7', '11', '2', '3', '8', '9', '10' ]` is as correct as the sample in that page. 

We could try and emulate `tsort(1)` if there is a compatibility issue / use case but I can't see why.

**Comment by bungle** [comment]
Yes, you are correct, it just felt wrong to not at least put those that don't depend on others at first. And those that do depend come before them just felt weird at first.
